```yaml
version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Sunil"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Firebase Functions dependencies  
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Sunil"
    commit-message:
      prefix: "deps"

  # Python agent dependencies
  - package-ecosystem: "pip"
    directory: "/agents/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Sunil"
    commit-message:
      prefix: "deps"

  # Java agent dependencies
  - package-ecosystem: "maven"
    directory: "/agents/java"
    schedule:
      interval: "weekly" 
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Sunil"
    commit-message:
      prefix: "deps"
```